---
title: "About LOOOP"
author: "Monica Matt"
output:
  html_document:
    toc: TRUE
---
# Lake Ontario, Oneida, Onondaga Program -- LOOOP

---  
<style type = "text/css">
  body{
  font-size: 12pt;
  }
</style>

## About the LOOOP  
The _**"Lake Ontario, Oneida, Onondaga Program (LOOOP)"**_ aims to provide high school teachers with the knowledge and resources to facilitate student-led investigations and discussions about environmental issues and stewardship relevant to the Great Lakes Basin. The Upstate Freshwater Institute (UFI), a not-for-profit corporation dedicated to advancing freshwater science and education in New York, began the LOOOP with nine partnering high schools across the region, the State University of New York College of Environmental Science and Forestry's Open Academy (SUNY-ESF OA), and the Onondaga-Cortland-Madison BOCES (OCM-BOCES) in 2021 with funding provided by the New York's Great Lakes Basin Small Grants Program.  

LOOOP promotes a student-centered approach to inquiry-based learning, allowing students to develop their own questions and take an active role in their own learning. Students are invited to participate in virtual discussions to learn more about the local environment, gain unique perspectives from people within the Lake Ontario watershed, and connect with other students other students during "LOOOP Chats". Students can also be involved by following the project on our project's social media pages.  
  
  
  Follow us @lake_looop on Instagram!