---
title: "Lake Levels"
author: "Adam Balogh"
output:
  html_document:
    toc: TRUE
---
# Lake Levels
##### *Adam Balogh; Student, State University of New York- College of Environmental Science and Forestry, Environmental Engineering*  
---  
<style type = "text/css">
  body{
  font-size: 12pt;
  }
</style>
  Water levels of lakes are influenced by many factors, each of which plays a part in determining the current levels of water. Key influences include precipitation, drought, snowmelt and runoff, evaporation, and withdrawal for human uses (1). Precipitation and drought (the lack of precipitation) have large impacts on lake levels. During periods of heavy precipitation, water can be directly added to the lakes or fall within the watershed and enter the lake eventually through its tributaries. Large amounts of precipitation can cause lake water levels to increase, and as temperatures rise in the spring, snowpack melts and typically increases the water levels. Evaporation and withdrawal for human uses can offer some counterbalance to the influx of water added through precipitation and snowmelt, and prevent lakes from becoming too full and flooding. Human uses include withdrawal for drinking, irrigation, or engineering and management activities such as dredging, the removal of sediment from the bottom of lakes (1).  
 
  The water levels and the temperature of lakes are good indicators of global warming and climate change in the region. As temperatures continue to rise, and weather patterns become more unpredictable, so will lake levels. Recently, warmer temperatures have caused increased rates of evaporation and lowered the water levels of many lakes in the area (1). In addition, warmer temperatures may mean less lake-effect snow, which will reduce water added via spring snow melts.  

  Despite the amount of precipitation experienced this year, many lakes in the area have had below average water levels for much of 2021. Lake Ontario, for most of the year, was below average between February and September, as measured by the [International Lake Ontario-St. Lawrence River Board] (https://ijc.org/en/loslrb/watershed/water-levels). Onondaga Lake has fluctuated between above and below average this year, with unpredictable levels observed after large storms; this data is collected by the [United States Geographic Survey] (https://waterdata.usgs.gov/monitoring-location/04240495/#parameterCode=62614&period=P365D). Oneida Lake has had inconsistent water levels over the past few years. For most of 2021, Oneida Lake has been above the maximum target levels, even going above the flood level for a brief period of time, as reported by the [New York State Canal Corporation] (https://www.canals.ny.gov/waterlevels/netdata/oneida-levels.pdf).  

  Lower lake levels in recent years have had impacts on not only wildlife and lake-effect snow, but also on recreational activities. As shorelines recede, areas that were once submerged and accessible to watercraft will no longer provide viable mooring or safe navigation. Additionally, important shoreline ecosystems are impacted. If low lake levels persist, shipping is expected to become more expensive and difficult, as cargo ships are being forced to reduce loads by over 5% (1). This increases the shipping costs, which in turn, are passed on to consumers. Disruptions similar to these are expected to continue as water levels continue to lower in inland lakes, with effects expected to worsen due to climate change. Lakes and rivers influence daily life in ways that many do not realize. For this reason, it is important to care for our planet and the climate to protect these delicate systems that many take for granted on a daily basis.  
  
  
  
### References:  
* Environmental Protection Agency. (April 2021). EPA. Retrieved November 3, 2021, from https://www.epa.gov/climate-indicators/great-lakes. 
