---
title: "Stream Descriptions"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_collapsed: TRUE
---


<style type = "text/css">
  body{
  font-size: 12pt;
  }
</style>

# Stream Monitoring Parameters and Their Importance to Water Quality

Studying the properties of water is essential to _**limnology**_ or the study of the biological, chemical, and physical features of fresh water (including streams and lakes). The foundation of life as we know it exists because of the unique properties of water! Many organisms depend on access to healthy waterways and our climate is even influenced by the presence of water. Globally, water mediates the climate due to its high specific heat or the amount of energy required to warm or cool down 1 gram of water by 1 degree Celsius. If you have ever traveled to the coast of an ocean or a large inland lake such as one of the Laurentian Great Lakes, you may have noticed that the air temperature is cooler near the water. On hot days the land and the air above land heats up faster than the waterbodies and cool air above them. As the warm air from the land rises, cool air from the water rushes in to replace that air.

On this page are descriptions of parameters commonly collected or measured as part of a stream monitoring program. When reading through these descriptions, think about how one parameter affect others!

## Temperature

Water temperature is one of the most critical factors driving the overall characteristics of a waterbody. Water density changes with water temperature, creating a unique phenomenon where cold, dense water underlies warmer upper layers during periods of high air temperature; this is known as "thermal stratification". Those who live in temperate regions are likely familiar with this if they have swam in a stratified body of water and dove down to the "thermocline" which is where the warm upper layer and cool bottom layer meet and temperature changes rapidly. When the air drops below freezing ice is formed at the surface because the density of ice is less than water. Perhaps more remarkably, under the ice water that is four degrees Celsius is actually the most dense as a result of chemical properties of water molecules. This unique trait results in a characteristic known as "reverse thermal stratification" where the warmest water (4°C) is on the bottom!!! Thermal stratification cannot always be observed in flowing waters, but may occur in deeper pools within stream reaches. Temperatures in streams can be influenced by the amount of shaded reaches, turbidity, stream discharge, and inputs to the stream (i.e., surface runoff, industrial/commercial discharge). 

Many organisms can only live in environments that maintain their optimal temperature requirements. For example, cold-water fishes, like trout and salmon, and macroinvertebrates are most active in colder waters (7-18 C or 45-65 F) and become stressed or perish when waters exceed their temperature threshold. 

## Dissolved Oxygen

Just as for terrestrial life, most biological life in water requires oxygen to survive. All waters contain dissolved chemical compounds like oxygen. If there a lot of other dissolved compounds in a stream, there is less room for oxygen. The amount of space available for dissolved compounds is impacted by temperature (with colder temperature water capable of holding more dissolved oxygen than warmer temperature water). The amount or concentration of dissolved oxygen in streams can be related to a number of factors both in and out of the stream. Oxygen levels will increase or be maintained by direct atmospheric absorption, turbulence, and aquatic photosynthesis. On the other hand, biological respiration and decomposition utilize dissolved oxygen, lowering the concentration. The amount of dissolved oxygen that water holds is one of the most important parameters of water quality. In streams, oxygen is critical to animal life and insufficient levels can result in a lack of biodiversity or acute aquatic organism die-offs.

## pH (Potential of Hydrogen)

Most people have been exposed to the idea of pH through the concept of acidity and may recognize that a low pH means that a solution is acidic. They may even know that a pH of 7.0 means that a solution is "neutral" and a pH greater than 7.0 is considered "basic". But what are these values relative to? The answer may seem somewhat complicated: pH is a measure of the concentration of hydrogen ions in solution. Remember that water is made up of two hydrogen atoms and one oxygen atom ( H2O). Water molecules can actually break apart into two parts (a free hydrogen H, and what is known as a hydroxide group (OH)), and when the pH is neutral the concentration of each of these is the same. Only in situations where a compound which increases the free hydrogen (aka an acid) or a compound which increases the hydroxide concentration (aka a base) is introduced does the pH of water change. 

This property of water plays an important role in waters' ability to hold other important compounds in solution, as well as to sustaining biological functions including respiration across gill membranes. A lower pH allows more compounds to be in solution, and also affects the bio-availability of dissolved compounds (the ability for a compound to be taken in by an organism). While understanding pH, how it is measured, what different values mean, and what impacts it in the environment can be difficult at first, a good starting point for understanding is that typical pH values in surface water (lakes, ponds, and rivers) ranges from about 6.0 - 8.0, and it is normal to observe moderate variability in pH levels during a single sample at various depths and or locations due to chemical, physical, and biological processes happening in the water. Very low (less than 5.0) or very high (above 9.0) pH reading are indicative of water quality impairment. For further explanation follow this link: [US Geological Survey: pH and Water]("https://www.usgs.gov/special-topics/water-science-school/science/ph-and-water")

## Alkalinity

Alkalinity is not a chemical in water, but more so a way to describe a property of water. It is the buffering capacity of water or the ability to neutralize acidic and basic inputs to maintain a stable pH. Waterbodies with high alkalinity are able to maintain their pH when acid is introduced via acid rain or wastewater. Streams may be more naturally alkaline (higher alkalinity) due to the local geology. Watersheds with natural deposits of limestone will be more alkaline than areas with different rock types because natural surface runoff over limestone carries calcium carbonate (CaCO3) to the waterway. This will increase both the pH and alkalinity. In central New York, waterways often have a total alkalinity over 400 mg/L; however in the Adirondacks and closer to New York City, lakes may be as low as < 50 mg/L. This parameter is important to measure the long-term stability of a waterway and evaluate how it may be impacted by human activities. Follow this [link]("https://www.usgs.gov/special-topics/water-science-school/science/alkalinity-and-water") for more information on alkalinity in US surface waters.

## Turbidity

Turbidity measures the relative clarity of water. Water clarity can be influenced by naturally present suspended or dissolved particles in the water, and can make water look cloudy or murky. Depending on the type of the particles in the water, the color and opacity will vary. Particles suspended in waterways that can cause turbidity include algae, plankton, clay, silt, and other fine compounds. 

While some turbidity may be natural, high turbidity is often associated with poor water quality. High turbidity in streams may be the result of surface runoff from agricultural or urban development. These human activities can affect the both the quantity and quality of water entering streams. For example, impervious surfaces do not allow water to infiltrate the ground, creating more surface runoff and may channel the water so that it flows faster and has more erosive power. Increased turbidity can harm aquatic ecosystems by damaging habitat, clogging fish gills and reducing available sunlight for photosynthesis.

## Nitrate and Nitrite

Nitrites (NO2) and nitrates (NO3) are two of the nitrogenous elements that are involved in the nitrogen cycle, or the process where nitrogen is converted into multiple chemical forms as it circulates between the terrestrial, aquatic, and atmospheric biospheres. Nitrates are often naturally higher than nitrites in waterbodies and are an essential nutrient for plants and algae. If there are too many nitrates then water quality problems may arise. Nitrates can accelerate eutrophication or when a waterbody become so enriched with nutrients that it causes plants and algae to grow excessively. These changes can cause environmental impacts including decreasing biodiversity and decreasing dissolved oxygen concentrations. Additionally, excessive nitrate concentrations can be harmful to humans if ingested! Nitrate levels may range between 0 and 5 mg/L or ppm in natural streams, and typically unpolluted waters have less than 1 mg/L or ppm of nitrate.

## Phosphate or Orthophosphate

In the 1970's in Canada's Experimental Lakes Area, it was demonstrated that phosphorus was limiting in most freshwater aquatic ecosystems through a series of whole lake experiments ([Clean Lakes Alliance - Phosphorus]("https://www.cleanlakesalliance.org/phosphorus/")). Since then researchers and natural resource managers alike have focused on reducing phosphorus inputs to freshwater systems with the goal of minimizing human-induced eutrophication and algal blooms. Orthophosphate or Phosphate is a form of phosphorus that is readily usable to primary producers like algae, and therefore is directly related to the capacity of a waterbody to support algal populations. Phosphorus can come from both natural inputs and human activity including: weathering, groundwater, agricultural and urban runoff, sewage and septic systems, and waterfowl waste. Waterbodies with high phosophorus concentrations may have decreased biodiversity and low dissolved oxygen concentrations. Because phosphate is a limiting nutrient, the concentration is often very low and even lower than the amount of nitrates. Streams' phosphate concentrations should ideally be < 0.1 mg/L or ppm, but may range in relation to upstream sources. 

## Chloride

Chloride is a chlorine ion (or form of chlorine that has gained an electron) that is often found in the natural environment as a salt (or a compound made of a cation/positive ion and anion/negative ion) such as sodium chloride, calcium chloride, or magnesium chloride. Sea water can contain up to 19,000 mg/L of chloride, whereas fresh water systems typically have less than 40 mg/L of chloride. High concentrations of chloride can be toxic to fish, aquatic organisms, and amphibians. Additionally, aquatic vegetation and streamside plants and trees can be damaged by excessive salt concentrations. While chlorides can originate from a variety of natural and human sources, this parameter is often measured during the winter to evaluate how road salt usage and run off affects streams. Click this link to learn about the Izaak Walton League's [Salt Watch](https://www.iwla.org/water/stream-monitoring/salt-watch) program and how you can get involved!

## Macroinvertebrates or Biological Indicators

Macroinvertebrates are animals that lack a backbone and are large enough to be seen without a microscope. This general group can include larvae of insects that have an aquatic stage in their lifecycles (like dragonflies, caddisflies, and mosquitos) or creatures that are permanently aquatic (like crayfish, snails, worms, and leeches). Macroinvertebrates typically live in the sediments (benthos) and are an important part of both the stream and lake food webs. Their community makeup or biodiversity can also tell us a lot about the water quality of a stream. Many macroinvertebrate species have strict environmental needs and are sensitive to changes in dissolved oxygen, pH, temperature, chloride, and turbidity. Because of this characteristic, assessing the number and type of macroinvertebrates in a stream can help assess water quality over time.

## Stream Hydrology (Velocity, Area, and Discharge)

Stream velocity is the speed at which water is moving. Water speed can be influenced by the slope of the land, obstacles in the stream, and total volume of water in a stream. The cross-sectional area of a stream refers to the size of the stream in relation to both the width and depth. Imagine cutting a slice through the stream from one bank to the other. The area is how much space that slice covers. While some streams may be narrow and deep others may be wide and shallow. Understanding the stream area can help assess how much water a stream can hold and how it interacts with its surroundings (flooding and erosion). 

Stream discharge or stream flow is the volume of water passing at a point in the stream over a period of time. Multiplying the stream velocity (m/s or ft/s) by the cross sectional area (square meters or square feet) results in the stream discharge (cubic m/s or cubic ft/s). This parameter is important for determining how much nutrients or pollutants are entering a downstream waterbody over a period of time (also known as loading). High discharge means a lot of water is flowing and both velocity and area may be high, while low discharge means less water is moving through the stream and both velocity and area may be low. 
